export const IDEAS = [
  {
    id: 111,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: true, text: "Tech" },
      { id: "tag-3", checked: true, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: true,
    votes: 3,
    creationDate: 1631995464712,
  },
  {
    id: 112,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: true, text: "Tech" },
      { id: "tag-3", checked: false, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: false,
    votes: 2,
    creationDate: 1631115464712,
  },
  {
    id: 113,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: false, text: "Improvement" },
      { id: "tag-4", checked: true, text: "Innovation" },
    ],
    liked: true,
    votes: 5,
    creationDate: 1631679464712,
  },
  {
    id: 114,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: true, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: true,
    votes: 1,
    creationDate: 1631555464712,
  },
  {
    id: 115,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: true, text: "Improvement" },
      { id: "tag-4", checked: true, text: "Innovation" },
    ],
    liked: false,
    votes: 7,
    creationDate: 1631335464712,
  },
  {
    id: 116,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: true, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: true,
    votes: 3,
    creationDate: 1631005464712,
  },
  {
    id: 117,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: false, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: true, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: true,
    votes: 10,
    creationDate: 1631795464712,
  },
  {
    id: 118,
    title: "idea 1",
    description: "description 1",
    tags: [
      { id: "tag-1", checked: true, text: "Feature" },
      { id: "tag-2", checked: false, text: "Tech" },
      { id: "tag-3", checked: false, text: "Improvement" },
      { id: "tag-4", checked: false, text: "Innovation" },
    ],
    liked: true,
    votes: 5,
    creationDate: 1631565464712,
  },
];

export const TAGS = [
  { id: "tag-1", checked: false, text: "Feature" },
  { id: "tag-2", checked: false, text: "Tech" },
  { id: "tag-3", checked: false, text: "Improvement" },
  { id: "tag-4", checked: false, text: "Innovation" },
];

export const FILTERS = [
  { id: "date-desc", text: "Creation date descending" },
  { id: "date-asc", text: "Creation date ascending" },
  { id: "votes-asc", text: "Votes ascending" },
  { id: "votes-desc", text: "Votes descending" },
];
