export const IDEAS = [
  {
    id: 1,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 3,
    creationDate: 1631995464712,
  },
  {
    id: 2,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: false,
    votes: 2,
    creationDate: 1631115464712,
  },
  {
    id: 3,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 5,
    creationDate: 1631679464712,
  },
  {
    id: 4,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 1,
    creationDate: 1631555464712,
  },
  {
    id: 5,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: false,
    votes: 7,
    creationDate: 1631335464712,
  },
  {
    id: 6,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 3,
    creationDate: 1631005464712,
  },
  {
    id: 7,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 10,
    creationDate: 1631795464712,
  },
  {
    id: 8,
    title: "idea 1",
    description: "description 1",
    tags: ["feature", "tech", "improvement"],
    liked: true,
    votes: 5,
    creationDate: 1631565464712,
  },
];

export const TAGS = [
  { id: "tag-1", text: "Tag 1" },
  { id: "tag-2", text: "Tag 2" },
  { id: "tag-3", text: "Tag 3" },
  { id: "tag-4", text: "Tag 4" },
  { id: "tag-5", text: "Tag 5" },
];

export const FILTERS = [
  { id: "date-asc", text: "Creation date ascending" },
  { id: "votes-asc", text: "Votes ascending" },
  { id: "date-desc", text: "Creation date descending" },
  { id: "votes-desc", text: "Votes descending" },
];
